---
abstract: 'A KeePass 2 agent'
author:
  - 'Charles McGarvey <ccm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-KeePass-Agent-KDBX
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  File::KeePass::Agent::KDBX:
    file: lib/File/KeePass/Agent/KDBX.pm
    version: '0.902'
recommends:
  Pod::Usage: '0'
requires:
  File::KeePass::Agent: '0'
  File::KeePass::KDBX: '0'
  Module::Load: '0'
  namespace::clean: '0'
  parent: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/chazmcgarvey/File-KeePass-Agent-KDBX/issues
  homepage: https://github.com/chazmcgarvey/File-KeePass-Agent-KDBX
  repository: https://github.com/chazmcgarvey/File-KeePass-Agent-KDBX.git
version: '0.902'
x_authority: cpan:CCM
x_generated_by_perl: v5.34.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
